# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Tests
on:
  workflow_dispatch:
  push:
    branches: [main, dev]
    paths:
      - '*.ts'
      - 'scripts/build.sh'
      - 'gh-page/**'

jobs:
  test-coverage:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Set up Node.js'
        uses: actions/setup-node@v5
        with:
          node-version: 23
          registry-url: https://registry.npmjs.org/

      - name: 'Install dependencies'
        run: npm install

      - name: 'Compile, build'
        run: npm run build

      - name: 'Test and report coverage'
        run: npm run coverage

      - name: 'Upload coverage report to coveralls.io'
        uses: coverallsapp/github-action@v2
        with:
          file: ./gh-page/coverage/clover.xml

      - name: 'Upload coverage reports to github pages'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-page
          commit_message: 'Coverage: ${{ github.event.head_commit.message }}'
